spring:
    application:
        name: springerapp
    datasource:
        url: jdbc:mysql://localhost:3306/springtester_db
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: kali
        password: kali

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: create-drop

security: 
    jwt:
        encryption-key: "1b0b7a4c6e8d1a6b8b4f5e4c2d3a1f4e3a7b6c5d8e1f2a0b3e4c5d6a7b8e9f0"
        
logging:
  level:
    '[org.hibernate.sql]': debug
    '[org.springframework.web]': debug
    root: info